SimplePointofSale/Models/Invoice.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace SimplePointofSale.Models
{
    public class Invoice
    {
        [DisplayName("Invoice Number")]
        public int InvoiceID { get; set; }
        [DisplayName("Customer ID")]
        public int CustomerID { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "Invoice Date")]
        public DateTime InvoiceDate { get; set; }

        public virtual Customer Customer { get; set; }
        public virtual ICollection<InvoiceLine> InvoiceLines { get; set; }


    }
}

SimplePointofSale/Controllers/CustomersController.cs
using System;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using SimplePointofSale.DAL;
using SimplePointofSale.Models;
using PagedList;

namespace SimplePointofSale.Controllers
{
    public class CustomersController : Controller
    {
        private PoSContext db = new PoSContext();

        // GET: Customers
        public ViewResult Index(string sortOrder, string CurrentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "LName_desc" : "";
            ViewBag.LNameSortParm = sortOrder == "LName" ? "Lmail_desc" : "LName";
            ViewBag.FNameSortParm = sortOrder == "FName" ? "FName_desc" : "FName";
            ViewBag.EmailSortParm = sortOrder == "Email" ? "Email_desc" : "Email";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = CurrentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            var customers = from s in db.Customers
                           select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                customers = customers.Where(s => s.LName.Contains(searchString)
                                       || s.FName.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "LName":
                    customers = customers.OrderBy(s => s.LName);
                    break;
                case "LName_desc":
                    customers = customers.OrderByDescending(s => s.LName);
                    break;
                case "FName":
                    customers = customers.OrderBy(s => s.FName);
                    break;
                case "FName_desc":
                    customers = customers.OrderByDescending(s => s.FName);
                    break;
                case "Email":
                    customers = customers.OrderBy(s => s.Email);
                    break;
                case "Email_desc":
                    customers = customers.OrderByDescending(s => s.Email);
                    break;
                default:
                    customers = customers.OrderBy(s => s.LName);
                    break;
            }
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(customers.ToPagedList(pageNumber, pageSize));
        }

        // GET: Customers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // GET: Customers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Customers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CustomerID,FName,LName,Email")] Customer customer)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Customers.Add(customer);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (DataException /* dex */)
            {
                //Log the error - UNCOMMENT dex, add line here to write to log
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
            }
            

            return View(customer);
        }

        // GET: Customers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        } 

        // POST: Customers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CustomerID,FName,LName,Email")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(customer);
        }

        // GET: Customers/Delete/5
        public ActionResult Delete(int? id, bool? saveChangesError = false)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (saveChangesError.GetValueOrDefault())
            {
                ViewBag.ErrorMessage = "Delete failed. Try again, and if the problem persists see your system administrator.";
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Customer customer = db.Customers.Find(id);
            db.Customers.Remove(customer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SimplePointofSale/Controllers/InvoicesController.cs
using System;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using SimplePointofSale.DAL;
using SimplePointofSale.Models;
using PagedList;

namespace SimplePointofSale.Views
{
    public class InvoicesController : Controller
    {
        private PoSContext db = new PoSContext();

        // GET: Invoices
        public ViewResult Index(string sortOrder, string CurrentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "Date_desc" : "";
            ViewBag.FNameSortParm = sortOrder == "FName" ? "fname_desc" : "FName";
            ViewBag.LNameSortParm = sortOrder == "LName" ? "lname_desc" : "LName";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = CurrentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            var invoices = db.Invoices.Include(s => s.Customer);
            

            if (!String.IsNullOrEmpty(searchString))
            {
                invoices = invoices.Where(s => s.Customer.LName.Contains(searchString)
                                       || s.Customer.FName.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "FName":
                    invoices = invoices.OrderBy(s => s.Customer.FName);
                    break;
                case "fname_desc":
                    invoices = invoices.OrderByDescending(s => s.Customer.FName);
                    break;
                case "LName":
                    invoices = invoices.OrderBy(s => s.Customer.LName);
                    break;
                case "lname_desc":
                    invoices = invoices.OrderByDescending(s => s.Customer.LName);
                    break;
                case "Date":
                    invoices = invoices.OrderBy(s => s.InvoiceDate);
                    break;
                case "date_desc":
                    invoices = invoices.OrderByDescending(s => s.InvoiceDate);
                    break;
                default:
                    invoices = invoices.OrderByDescending(s => s.InvoiceDate);
                    break;
            }
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(invoices.ToPagedList(pageNumber, pageSize));
        }

        // GET: Invoices/Details/5
        public ActionResult Details(String referrer, int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invoice invoice = db.Invoices.Find(id);
            if (invoice == null)
            {
                return HttpNotFound();
            }
            ViewBag.referrer = referrer;
            return View(invoice);
        }

        // GET: Invoices/Create
        public ActionResult Create()
        {
            ViewBag.CustomerID = new SelectList(db.Customers, "CustomerID", "FullName");
            return View();
        }

        // POST: Invoices/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "InvoiceID,CustomerID,InvoiceDate")] Invoice invoice)
        {
            if (ModelState.IsValid)
            {
                db.Invoices.Add(invoice);
                db.SaveChanges();
                return RedirectToAction("Details", new { id = invoice.InvoiceID});
            }

            ViewBag.CustomerID = new SelectList(db.Customers, "CustomerID", "FullName", invoice.CustomerID);
            return View(invoice);
        }

        // GET: InvoiceLines/Create
        public ActionResult CreateInvoiceLine(String invoiceID)
        {
            var InvoiceID = Request["invoiceID"];
            if (InvoiceID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invoice invoice = db.Invoices.Find(Convert.ToInt32(InvoiceID));
            if (invoice == null)
            {
                return HttpNotFound();
            }
            ViewBag.InvoiceID = Convert.ToInt32(InvoiceID);
            ViewBag.ProductID = new SelectList(db.Products, "ProductID", "ProductFullName");
            return View();
        }

        // POST: InvoiceLines/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateInvoiceLine([Bind(Include = "InvoiceLineID,InvoiceID,ProductID,Quantity,PriceAtSale")] InvoiceLine invoiceLine)
        {
            if (ModelState.IsValid)
            {
                db.InvoiceLines.Add(invoiceLine);
                db.SaveChanges();
                return RedirectToAction("Details", new { id = invoiceLine.InvoiceID });
            }
            ViewBag.ProductID = new SelectList(db.Products, "ProductID", "ProductFullName", invoiceLine.ProductID);
            return View(invoiceLine);
        }

        // GET: Invoices/Edit/5
        public ActionResult Edit(String referrer, int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invoice invoice = db.Invoices.Find(id);
            if (invoice == null)
            {
                return HttpNotFound();
            }
            ViewBag.referrer = referrer;
            ViewBag.CustomerID = new SelectList(db.Customers, "CustomerID", "FullName", invoice.CustomerID);
            return View(invoice);
        }

        // POST: Invoices/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "InvoiceID,CustomerID,InvoiceDate")] Invoice invoice)
        {
            if (ModelState.IsValid)
            {
                db.Entry(invoice).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", new { id = invoice.InvoiceID });
            }
            ViewBag.CustomerID = new SelectList(db.Customers, "CustomerID", "FullName", invoice.CustomerID);
            return View(invoice);
        }

        // GET: Invoices/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invoice invoice = db.Invoices.Find(id);
            if (invoice == null)
            {
                return HttpNotFound();
            }
            return View(invoice);
        }

        // POST: Invoices/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Invoice invoice = db.Invoices.Find(id);
            db.Invoices.Remove(invoice);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Invoices/DeleteInvoiceLine/5
        public ActionResult DeleteInvoiceLine(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            InvoiceLine invoiceLine = db.InvoiceLines.Find(id);
            ViewBag.InvoiceID = invoiceLine.InvoiceID;
            if (invoiceLine == null)
            {
                return HttpNotFound();
            }
            return View(invoiceLine);
        }

        // POST: Invoices/DeleteInvoiceLine/5
        [HttpPost, ActionName("DeleteInvoiceLine")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteInvoiceLineConfirmed(int id)
        {
            InvoiceLine invoiceLine = db.InvoiceLines.Find(id);
            var returnID = invoiceLine.InvoiceID;
            db.InvoiceLines.Remove(invoiceLine);
            db.SaveChanges();
            return RedirectToAction("Details", new { id = returnID });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SimplePointofSale/Views/Invoices/CreateInvoiceLine.cshtml
@model SimplePointofSale.Models.InvoiceLine

@{
    ViewBag.Title = "Add Line To Invoice";
}

<h2>Add Line To Invoice</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Select a product, quantity, and price for this invoice line.</h4>
        <hr />
        <input Length="16" class="input-validation-error" data-val="true" data-val-number="The field Invoice Number must be a number." data-val-required="The Invoice Number field is required." id="InvoiceID" name="InvoiceID" type="hidden" value="@ViewBag.InvoiceID" />
        @*@Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.InvoiceID, "@Model.InvoiceID")*@

        <div class="form-group">
            @Html.LabelFor(model => model.ProductID, "ProductID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProductID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProductID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PriceAtSale, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PriceAtSale, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PriceAtSale, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Cancel", "Details", new { id = ViewBag.InvoiceID }, new { @class = "btn btn-warning" })
</div>

SimplePointofSale/Views/Invoices/DeleteInvoiceLine.cshtml
@model SimplePointofSale.Models.InvoiceLine

@{
    ViewBag.Title = "DeleteInvoiceLine";
}

<h2>Delete Invoice Line</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>This operation can't be undone.</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.Product.Brand)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product.Brand)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PriceAtSale)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PriceAtSale)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            @Html.ActionLink("Cancel", "Details", new { id = ViewBag.InvoiceID }, new { @class = "btn btn-warning" })
            <input type="submit" value="Delete" class="btn btn-danger" />
        </div>
    }
</div>

SimplePointofSale/Views/Invoices/Details.cshtml
@model SimplePointofSale.Models.Invoice

@{
    ViewBag.Title = "Details";
}

<h2>Company Name</h2>
<address>
    Company Address<br />
    City, State ZIP<br />
    Phone Number
</address>

<div>
    <h4>Invoice</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Bill To
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer.FullName)
        </dd>
        <dd>
            @Html.DisplayFor(model => model.Customer.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InvoiceDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InvoiceDate)
        </dd>
        <dd>
        @{
            decimal subTotal = 0.00m;
            foreach (var item in Model.InvoiceLines)
            {
                subTotal = subTotal + item.LineTotal;
            }
            decimal taxTotal = 0.06m * subTotal;
            decimal finalTotal = taxTotal + subTotal;
        }
            <table class="table">
                <tr>
                    <th>Brand</th>
                    <th>Name</th>
                    <th>Price</th>
                    <th>Quantity</th>
                    <th>Total Price</th>
                    <th></th>
                </tr>
                
                @foreach (var item in Model.InvoiceLines)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Product.Brand)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Product.ProductName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PriceAtSale)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Quantity)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.LineTotal)
                        </td>
                        <td class="no-print">
                            @Html.ActionLink("Delete", "DeleteInvoiceLine", new { id = item.InvoiceLineID }, new { @class = "btn btn-danger btn-xs" })
                        </td>
                    </tr>
                }
                <tr class="no-print">
                    <td>@Html.ActionLink("Add Line", "CreateInvoiceLine", new { invoiceID = Model.InvoiceID }, new { @class = "btn btn-success btn-xs" })</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr id="invoice_total">
                    <td>
                    </td>
                </tr>
                <tr id="invoice_total">
                    <td></td>
                    <td></td>
                    <td></td>
                    <th>
                        Subtotal:
                    </th>
                    <td>
                        @subTotal.ToString("C2")
                    </td>
                    <td></td>
                </tr>
                <tr id="invoice_total">
                    <td></td>
                    <td></td>
                    <td></td>
                    <th>
                        Tax (PA):
                    </th>
                    <td>
                        @taxTotal.ToString("C2")
                    </td>
                    <td></td>
                </tr>
                <tr id="invoice_total">
                    <td></td>
                    <td></td>
                    <td></td>
                    <th>
                        Total:
                    </th>
                    <td>
                        @finalTotal.ToString("C2")
                    </td>
                    <td></td>
                </tr>
            </table>
        </dd>
    </dl>

</div>
<p class="no-print">
    @Html.ActionLink("Edit Details", "Edit", new { id = Model.InvoiceID, referrer = Model.InvoiceID }, new { @class = "btn btn-default" })
    <a class="btn btn-primary" onclick="myPrint()">Print Invoice</a>
    @Html.ActionLink("Save and Close", "Index", null, new { @class = "btn btn-primary" })
    @if (ViewBag.referrer != null)
    {
        @Html.ActionLink("Back to Customer", "Details", "Customers", new { id = ViewBag.referrer }, new { @class = "btn btn-default" })
    }
</p>

<script>
function myPrint() {
    window.print();
}
</script>

SimplePointofSale/Views/Invoices/Edit.cshtml
@model SimplePointofSale.Models.Invoice

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Invoice</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.InvoiceID)

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerID, "CustomerID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CustomerID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CustomerID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.InvoiceDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.InvoiceDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.InvoiceDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @if (ViewBag.referrer != null)
    {
        @Html.ActionLink("Cancel", "Details", "Invoices", new { id = ViewBag.referrer }, new { @class = "btn btn-warning" })
    }
    else
    {
        @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-warning" })
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}